In [27]:
import pandas as pd

In [28]:
df=pd.read_csv('amazon_product.csv')

In [29]:
df.head(6)

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
5,5,B0CSB22F9C,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$129.99,$137.65,USD,4.2,578,https://www.amazon.com/dp/B0CSB22F9C,https://m.media-amazon.com/images/I/51rp0nqaPo...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN

In [30]:
df.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='object')

In [31]:
df=df.drop(columns={'product_url','product_photo'})

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   64 non-null     int64
 1   asin                         64 non-null     object
 2   product_title                64 non-null     object
 3   product_price                64 non-null     object
 4   product_original_price       27 non-null     object
 5   currency                     64 non-null     object
 6   product_star_rating          54 non-null     float64
 7   product_num_ratings          64 non-null     int64
 8   product_num_offers           64 non-null     int64
 9   product_minimum_offer_price  64 non-null     object
 10  is_best_seller               64 non-null     bool
 11  is_amazon_choice             64 non-null     bool
 12  is_prime                     64 non-null     bool
 13  climate_pledge_friendly      64 non-null     bool
 14  sales_volume                 61 non-null     object
 15  delivery                     63 non-null     object
 16  has_variations               64 non-null     bool
 17  product_availability         1 non-null      object
 18  unit_price                   5 non-null      object
 19  unit_count                   5 non-null      float64
dtypes: bool(5), float64(2), int64(3), object(10)
memory usage: 7.9+ KB

In [33]:
df=df.drop(columns={'product_availability','unit_price','unit_count' })

In [34]:
df.isnull().sum()

Unnamed: 0                      0
asin                            0
product_title                   0
product_price                   0
product_original_price         37
currency                        0
product_star_rating            10
product_num_ratings             0
product_num_offers              0
product_minimum_offer_price     0
is_best_seller                  0
is_amazon_choice                0
is_prime                        0
climate_pledge_friendly         0
sales_volume                    3
delivery                        1
has_variations                  0
dtype: int64

In [35]:
df['product_price'].str.split('$').str[1].str.strip()

0      99.99
1     149.74
2      49.88
3     335.00
4     199.99
       ...
59     34.98
60     14.99
61      0.00
62     69.99
63     59.99
Name: product_price, Length: 64, dtype: object

In [36]:
df['product_price']=df['product_price'].str.split('$').str[1].str.strip()

In [37]:
df['product_original_price'].str.split('$').str[1].str.strip()

0     169.99
1     158.00
2        NaN
3     499.00
4        NaN
       ...
59       NaN
60     30.00
61       NaN
62       NaN
63     84.99
Name: product_original_price, Length: 64, dtype: object

In [38]:
df['product_original_price']=df['product_original_price'].str.split('$').str[1].str.strip()

In [39]:
df['product_original_price']=pd.to_numeric(df['product_original_price'],errors='coerce')

In [40]:
df['product_original_price'].fillna(df['product_original_price'].median(),inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_22972\1669427019.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['product_original_price'].fillna(df['product_original_price'].median(),inplace=True)

In [41]:
df['product_minimum_offer_price']=df['product_minimum_offer_price'].str.split('$').str[1].str.strip()
df.head(7)

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,169.99,USD,4.0,2929,10,64.89,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,158.00,USD,4.2,135,8,145.87,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,56.95,USD,3.9,205,1,49.88,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,499.00,USD,4.3,2248,30,289.99,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,56.95,USD,4.1,423,2,150.09,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True
5,5,B0CSB22F9C,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",129.99,137.65,USD,4.2,578,13,128.12,False,False,True,False,3K+ bought in past month,"FREE delivery Tue, Aug 6",False
6,6,B0CV4NQYFP,"SAMSUNG Galaxy A35 5G A Series Cell Phone, 128...",349.99,399.99,USD,4.4,109,2,267.01,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6 Or fastest delivery M...",True

In [49]:
df=df.drop(columns=['sales_volume'])

In [50]:
df.isnull().sum()

Unnamed: 0                      0
asin                            0
product_title                   0
product_price                   0
product_original_price          0
currency                        0
product_star_rating            10
product_num_ratings             0
product_num_offers              0
product_minimum_offer_price     0
is_best_seller                  0
is_amazon_choice                0
is_prime                        0
climate_pledge_friendly         0
delivery                        1
has_variations                  0
dtype: int64

In [52]:
df['product_star_rating'].fillna(df['product_star_rating'].median(),inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_22972\121794087.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['product_star_rating'].fillna(df['product_star_rating'].median(),inplace=True)

In [53]:
df['delivery']

0                              FREE delivery Tue, Aug 6
1     FREE delivery Wed, Aug 7 Only 7 left in stock ...
2                              FREE delivery Tue, Aug 6
3                               FREE delivery Aug 6 - 8
4                              FREE delivery Tue, Aug 6
                            ...
59    FREE delivery on $35 shipped by Amazon.This ti...
60                                  Available instantly
61            Available instantly on compatible devices
62    FREE deliveryThis item will be released on Aug...
63                                        FREE delivery
Name: delivery, Length: 64, dtype: object